alias git-status-uno='git status -uno'
alias run-commits-script='make-commits-script > /c/temp/commits.sh && nano /c/temp/commits.sh && /c/temp/commits.sh'
alias ant-clean-dev='ant clean dev'
alias ant-no-gwt='ant -Dskip.gwt=true'
alias ant-refresh-projects='ant -Dmaven.quick=true -Dproject.refs=true eclipse-projects-clean eclipse-projects'
alias ant-restart-db='ant-stop-db && ant-start-db'
alias ant-start-db='ant start-k && ant start-rdbms'
alias ant-stop-db='ant stop-k && ant stop-rdbms'
alias antt='ant -Dmaven.quick=true -Dproject.refs=true'
alias cls='clear'
alias edit-bashrc='edit_bashrc_func'
alias g='git'
alias g-add='git add'
alias g-amend='git commit --amend'
alias g-commit='git commit'
alias g-diff-staged='git diff --staged'
alias g-log='git log'
alias g-status='git status'
alias g-unstage='git reset HEAD'
alias git-current-branch='git rev-parse --abbrev-ref HEAD'
alias git-diff-staged='git diff --staged'
alias git-log-one-author='git log --pretty=format:"%h %an %ad %s" --date=short'
alias git-status-uno='git status -uno'
alias git-unstage='git reset HEAD'
alias load-bashrc='source $HOME/.bashrc'
alias mysql_connect='mysql.exe --host=localhost --password=appian --user=appian --port=3306 --protocol=tcp'
alias nano='nano -F'
alias rm_merge_files='rm -f `find | grep ".*\.\(REMOTE\|LOCAL\|BASE\).*\.java"`'
alias run-commits-script='make-commits-script > /c/temp/commits.sh && nano /c/temp/commits.sh && /c/temp/commits.sh'
alias search='find -iregex'
alias search-history='history | grep -v history | grep '
alias top_ten='history | sed '\''s/^ \+//;s/  / /'\'' | cut -d'\'' '\'' -f2- | awk '\''{ count[$0]++ } END { for (i in count) print count[i], i }'\'' | sort -rn |head -10'
alias vdir='ls --color=auto --format=long'
alias watch='$HOME/bin/watch'
alias webserver='python -m SimpleHTTPServer'
alias wget_appian='wget_page http://localhost:8080/ae/tempo'
alias wget_page='wget -q -O -'
alias appian-openvpn='sudo openvpn --script-security 2 --up /etc/openvpn/openvpn-dns --down /etc/openvpn/openvpn-dns --config ~/.openvpn/client.ovpn'
alias copy-to-clip="perl -pe 'chomp if eof' | xclip -sel clip"
