
alias git-status-uno='git status -uno'
alias tasklist-java='tasklist | grep "PID\|java"'
alias run-commits-script='make-commits-script > /c/temp/commits.sh && nano /c/temp/commits.sh && /c/temp/commits.sh'
alias a='cd /cygdrive/a/'
alias ant-clean-dev='ant clean dev'
alias ant-no-gwt='ant -Dskip.gwt=true'
alias ant-refresh-projects='ant -Dmaven.quick=true -Dproject.refs=true eclipse-projects-clean eclipse-projects'
alias ant-restart-db='ant-stop-db && ant-start-db'
alias ant-start-db='ant start-k && ant start-rdbms'
alias ant-stop-db='ant stop-k && ant stop-rdbms'
alias antt='ant -Dmaven.quick=true -Dproject.refs=true'
alias apt-get='apt-cyg -m http://mirror.symnds.com/software/cygwin/x86_64/'
alias c='cd /cygdrive/c/'
alias cdd='cd_func'
alias cls='clear'
alias cp='cp -i'
alias d='cd /cygdrive/d/'
alias df='df -h'
alias dir='ls --color=auto --format=vertical'
alias du='du -h'
alias echo='echo -n'
alias edit-bashrc='edit_bashrc_func'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias g='git'
alias g-add='git add'
alias g-amend='git commit --amend'
alias g-commit='git commit'
alias g-diff-staged='git diff --staged'
alias g-log='git log'
alias g-status='git status'
alias g-unstage='git reset HEAD'
alias git-current-branch='git rev-parse --abbrev-ref HEAD'
alias git-diff-staged='git diff --staged'
alias git-log-one-author='git log --pretty=format:"%H %an %ad" --date=short'
alias git-status-uno='git status -uno'
alias git-unstage='git reset HEAD'
alias grep='grep --color'
alias l='ls -CF'
alias la='ls -A'
alias less='less -r'
alias ll='ls -l'
alias load-bashrc='source $HOME/.bashrc'
alias ls='ls -hF --color=tty'
alias mgit='/cygdrive/c/Program\ Files\ \(x86\)/Git/bin/git.exe'
alias multipane='tmux new -s CYGWIN'
alias mv='mv -i'
alias mysql_connect='mysql.exe --host=localhost --password=appian --user=appian --port=3306 --protocol=tcp'
alias nano='nano -F'
alias rm='rm -i'
alias rm_merge_files='rm -f `find | grep ".*\.\(REMOTE\|LOCAL\|BASE\).*\.java"`'
alias run-commits-script='make-commits-script > /c/temp/commits.sh && nano /c/temp/commits.sh && /c/temp/commits.sh'
alias search='find -iregex'
alias search-history='history | grep -v history | grep '
alias tasklist-java='tasklist | grep "PID\|java"'
alias tmux-restart='rm -rf /tmp/tmux* && tmux start-server'
alias top_ten='history | sed '\''s/^ \+//;s/  / /'\'' | cut -d'\'' '\'' -f2- | awk '\''{ count[$0]++ } END { for (i in count) print count[i], i }'\'' | sort -rn |head -10'
alias vdir='ls --color=auto --format=long'
alias watch='$HOME/bin/watch'
alias webserver='python -m SimpleHTTPServer'
alias wget_appian='wget_page http://localhost:8080/ae/tempo'
alias wget_page='wget -q -O -'
alias whence='type -a'
alias winpath='cygpath -a -w'
alias z='cd /cygdrive/z/'
