#!/bin/sh

## Environment variables
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
# export XKL_MODMAP_DISABLE=1

## global sessions and configuration
touch "${HOME}/.vnc/.startup.log"
[ -x /etc/vnc/xstartup ] && /etc/vnc/xstartup
[ -r "${HOME}/.Xresources" ] && xrdb "${HOME}/.Xresources"

## sessions and configurations
vncconfig -iconic &
gnome-session --session=gnome-fallback &

vnc_index=$(echo "$DISPLAY" | grep -o '[0-9]')
export TMUX_INIT_SESSION="vnc-${vnc_index}"
[ -x "${HOME}/.xinitrc" ] && "${HOME}/.xinitrc"

## visual components
# none so far

# common applications
gnome-terminal --display "${DISPLAY}"

## user installed applications
type kupfer >/dev/null 2>&1 && kupfer &
