#!/bin/sh

STARTUP_LOG="${HOME}/.vnc/startup.log"
touch "${STARTUP_LOG}"

log() {
  echo "vnc startup: $1" >> "${STARTUP_LOG}"
}

## Environment variables
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export XKL_MODMAP_DISABLE=1

## global sessions and configuration
if [ -x /etc/vnc/xstartup ]; then
  log "Running /etc/vnc/xstartup"
  /etc/vnc/xstartup
fi

if [ -r "${HOME}/.Xresources" ]; then
  log "Running xrdb ${HOME}/.Xresources"
  xrdb "${HOME}/.Xresources"
fi

## sessions and configurations
log "Running vncconfig -iconic"
vncconfig -iconic &
# gnome-session --session=gnome-fallback &
# cinnamon-session-cinnamon2d --failsafe --display="${DISPLAY}" &
log "Running xsetroot -solid grey"
xsetroot -solid grey

vnc_index=$(echo "${DISPLAY}" | grep -o '[0-9]')
export TMUX_INIT_SESSION="vnc-${vnc_index}"
export TMUX=""

if [ -x "${HOME}/.xinitrc" ]; then
  log "Running ${HOME}/.xinitrc"
  "${HOME}/.xinitrc"
fi

if [ -x "${HOME}/.xsession" ]; then
  log "Running ${HOME}/.xsession"
  "${HOME}/.xsession"
fi

## visual components
type conky >/dev/null 2>&1 && \
  conky --display="${DISPLAY}" --config="${HOME}/.quotes.conkyrc"\
  --double-buffer --daemonize &>>"${STARTUP_LOG}"

# common applications
#log "Running gnome-terminal"
#gnome-terminal --display "${DISPLAY}" &>>"${STARTUP_LOG}" &

## user installed applications
# TODO: Consider using kupfer.
type kupfer >/dev/null 2>&1 && \
  kupfer &>>"${STARTUP_LOG}" &
type xbindkeys_autostart >/dev/null 2>&1 && \
  xbindkeys_autostart &>>"${STARTUP_LOG}"
type xmodmap >/dev/null 2>&1 && [ -f "${HOME}/.Xmodmap_vnc" ] &&\
    xmodmap -display "${DISPLAY}" "${HOME}/.Xmodmap_vnc"

log "Running startxfce4 &" 
startxfce4
