#!/bin/sh

STARTUP_LOG="${HOME}/.vnc/startup.log"
touch "${STARTUP_LOG}"
function log () {
  echo "vnc startup: $1" >> "${STARTUP_LOG}"
}

## Environment variables
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
# export XKL_MODMAP_DISABLE=1

## global sessions and configuration
[ -x /etc/vnc/xstartup ] && /etc/vnc/xstartup
[ -r "${HOME}/.Xresources" ] && xrdb "${HOME}/.Xresources"

## sessions and configurations
vncconfig -iconic &
# gnome-session --session=gnome-fallback &
cinnamon-session-cinnamon2d --failsafe --display="${DISPLAY}" &

vnc_index=$(echo "${DISPLAY}" | grep -o '[0-9]')
export TMUX_INIT_SESSION="vnc-${vnc_index}"
export TMUX=""
[ -x "${HOME}/.xinitrc" ] && "${HOME}/.xinitrc"

# common applications
gnome-terminal --display "${DISPLAY}" &

## user installed applications
type kupfer &>/dev/null && kupfer &
xbindkeys_autostart

## visual components
type conky && conky -X "${DISPLAY}" -d -c "${HOME}/.quotes.conkyrc"
