#!/usr/bin/env bash

[[ -z "${XPRA_DISPLAY}" ]] && XPRA_DISPLAY=":100"

if [[ $# -eq 0 ]]; then
  echo "You must provide the command to execute an X App." >&2
  exit 1
fi

DISPLAY="${XPRA_DISPLAY}" "$@"
